name: hugo-remote

on:
  push:
    branches:
      - master

# Don't forget to set these!
env:
  REMOTE: # username/username.github.io.git
  DEST: # public

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: 🔨 Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 🔧 Install tools
        run: |
          sudo apt install curl jq
          npm install postcss-cli autoprefixer
      - name: 🤵 Install latest Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -6}_Linux-64bit.tar.gz | tar -xvzf-
          sudo mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/
          hugo version
      - name: 👯 Clone remote repository
        run: git clone https://github.com/${REMOTE} ${DEST}
      - name: 🧹 Clean site
        run: |
          if [ -d "${DEST}" ]; then
            rm -rf ${DEST}/*
          fi
      - name: 🍳 Build site
        run: hugo ${HUGO_ARGS:-""} -d ${DEST}
      - name: 🎁 Publish to remote repository
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd ${DEST}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git status
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push -f -q https://${{ secrets.TOKEN }}@github.com/${REMOTE} master
